title: Bruno Brasil - Desenvolvimento de Robôs de Investimentos  
description: > # this means to ignore newlines until "baseurl:"
  Desenvolvedor de Software & Expert Advidor especialista em Robôs de Investimentos para o mercado Forex. Se você tem uma estratégia e quer automatizar fale comigo.
permalink: ':title/'
baseurl: "/" # the subpath of your site, e.g. /blog
url: "http://brunobrasil.dev" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: https://twitter.com/brunobrasilweb #if your site has a twitter account, enter it here

# Author Settings
author: Bruno Brasil # add your name
author-img: bruno-brasil.jpg # add your photo
about-author: Desenvolvedor de Expert Advidor para Forex. <br> (Robôs de Investimentos) # add description
social-twitter: brunobrasildev # add your Twitter handle
social-facebook: brunobrasilweb # add your Facebook handle
social-github: brunobrasildev # add your Github handle
social-linkedin: bruno-brasil-89b67430 # add your Linkedin handle
social-email: contato@brunobrasil.dev # add your Email address

# Disqus
discus-identifier: brunobrasilweb # add your discus identifier

# Tracker
analytics: UA-119520059-1 # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
